### ISSUE TITLE
Transparent png are not properly handled

### ISSUE THREAD

**Issue by bobifle** [EttienneS/AnimatedTokenMaker#15]
Here's an example of token border 
![token-border](https://user-images.githubusercontent.com/26679634/112967323-749db780-914b-11eb-836f-858f822c7e3a.png)

for which the transparency is not properly handled, when generating the token, the layer is completely masked.

**Comment by EttienneS** [comment]
Hi @bobifle 

Thanks for the feedback, the current system works with the alpha of the image, all the other tokens have a very low alpha 'center' so anything with an alpha below 5 is removed.  So if you take that image and just fill the center with very low alpha 'black' it should work fine.

But this has some drawbacks as more intricate borders look strange.  So to close this item I will be making a change to how all borders work.  Each border should have 2 images, one the actual border and the other the mask, which will be a black and white copy of the image where everything in white is drawn and black is removed.  This should give us much more flexibility in the borders and look a bit better.

Watch this item to see when the PR to close is in.
