### ISSUE TITLE
Borders / tokens are not proprely centered

### ISSUE THREAD

**Issue by bobifle** [EttienneS/AnimatedTokenMaker#17]
V0.2.0

Generated webm animated tokens do not seems properly centered, at least with the squared border.

![image](https://user-images.githubusercontent.com/26679634/114317306-ba715d00-9b07-11eb-9f20-022ae8a47f2c.png)

**Comment by bobifle** [comment]
github wont let me upload the webm file...

Here blue and red distance don't seem equal, not sure if this is because of the casted shadow, even so there's seems to be a small offset.

![image](https://user-images.githubusercontent.com/26679634/114317425-5733fa80-9b08-11eb-8e9e-30d3019d9927.png)

**Comment by EttienneS** [comment]
Good spot, they are both off because of the shadow, I am going to trim the default tokens to be centered and try to add one or two more border options to address this issue.
