### ISSUE TITLE
The app only generates 5 sec of webm animation

### ISSUE THREAD

**Issue by bobifle** [EttienneS/AnimatedTokenMaker#18]
V0.2.0

Using a mp4 of 17 sec, setting the clip length to 17, the final results only last for 5 sec.

**Comment by EttienneS** [comment]
Hi

This is some weird UI behavior, if the clip length changes at all the entire clip needs to be reloaded as we strip the frames on the initial adding of the clip.

This button is there to do that:
![image](https://user-images.githubusercontent.com/3992796/114561910-4e5d3900-9c6e-11eb-899b-932aa3a93cc8.png)

But nothing really gives you any indication that it should be clicked, and if it is clicked everything just kinda freezes up a bit before it works again.  The same goes for the 'Start at second' box.

To address this I am going to make the clip automatically reload if the textbox loses focus and I am going to try to give some indication that the reload is busy as to not confuse the user when the app locks up.

**Comment by EttienneS** [comment]
Closed in #20
