### ISSUE TITLE
Could we get numerical controls of the layers ?

### ISSUE THREAD

**Issue by bobifle** [EttienneS/AnimatedTokenMaker#19]
By that I mean slide are working fine, but it's sometimes tedious when you want to be really precise and go step by step.
Could we get a input field to enter the actual value ?

**Comment by EttienneS** [comment]
Yes this is a very good idea, it is rather finicky.  I am going to try to make it that you can also drag over the image to pan it around, as that may make it a bit faster to move things.

**Comment by EttienneS** [comment]
Closed in #20
