### ISSUE TITLE
Animated Tokens Become Static After 4s

### ISSUE THREAD

**Issue by LoneWolf80** [EttienneS/AnimatedTokenMaker#9]
Images generated in the /output/ folder from t0101.png onward are all copies of t0101.png. This results in animated tokens that "become static" after around the 4s mark, regardless of config file edits.

**Comment by EttienneS** [comment]
Thanks for the feedback, I see the problem.  There is a bit of leftover code from v1 that was trying to scale the image to fit in 100 frames.  So at 25fps anything over 4 seconds makes the count go over and it defaults back to just showing frame 0.

I published a new release to address the problem.

Let me know if you still run into any issues.

Thanks!
